---
- name: Reload nginx
  ansible.builtin.command: nginx -s reload
  become: true
  changed_when: true
  listen: reload nginx

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  listen: restart nginx
