---
- name: Configure restic repository secret for {{ secret.key }}
  block:
    - name: Encrypt secret with systemd-creds
      community.general.systemd_creds_encrypt:
        name: "{{ repo_dir | basename }}-{{ secret.key }}"
        secret: "{{ secret.value }}"
      register: encrypted_secret
      no_log: true
      become: true

    - name: Create credentials file
      ansible.builtin.copy:
        dest: "{{ repo_dir }}/{{ secret.key }}"
        content: "{{ encrypted_secret.value }}"
        mode: '0750'
        owner: "{{ restic_user }}"
        group: "{{ restic_user }}"
      become: true
