---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set:
  - pipefail
shopt:
  - globstar

vars:
  ANSIBLE_DIR: "{{ .ROOT_DIR }}/ansible"

includes:
  ansible:
    taskfile: .taskfiles/ansible/Taskfile.yaml
    dir: "{{ .ANSIBLE_DIR }}"
  restic:
    taskfile: .taskfiles/restic/Taskfile.yaml

tasks:
  default:
    silent: true
    cmd: task --list
