---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
  changed_when: false
  tags: &tags
    - deploy
    - config

- name: Reload Caddy
  ansible.builtin.command:
    cmd: "{{ caddy_bin_dir }}/caddy reload --config {{ caddy_config_file }}"
  become: true
  changed_when: false
  tags: *tags

- name: Restart Caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
  become: true
  tags: *tags
