---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  INVENTORY_DIR: "inventory"

tasks:
  generate-config:
    desc: Generate configuration files
    summary: |-
      This task generates group/host variables by injecting 1Password secrets
      into the configuration files. For a single group/host, pass
      GROUPNAME/HOSTNAME variable.
    preconditions:
      - which op
      - op user get --me
      - sh: '[ -z "{{ .GROUPNAME }}" ] || [ -z "{{ .HOSTNAME }}" ]'
        msg: "Cannot specify both GROUPNAME and HOSTNAME at the same time"
    vars:
      OBJNAME: "{{ if .GROUPNAME }}{{ .GROUPNAME }}{{ else }}{{ .HOSTNAME }}{{ end }}"
      CONFIG_DIR: files/{{ if .GROUPNAME }}group{{ else if .HOSTNAME }}host{{ else }}*{{ end }}_config
      CONFIG_FILES:
        sh: ls {{ .CONFIG_DIR }}/{{ .OBJNAME | default "*" }}.yml
    cmds:
      - for:
          var: CONFIG_FILES
        task: _generate_config
        vars:
          CONFIGFILE: "{{ .ITEM }}"
          OBJNAME: '{{ .ITEM | base | trimSuffix ".yml" }}'

  _generate_config:
    internal: true
    desc: Generate configuration file
    requires:
      vars:
        - CONFIGFILE
        - OBJNAME
    vars:
      ISGROUP: '{{ .CONFIGFILE | contains "/group_config/" }}'
      OUTPUT_DIR: '{{ .INVENTORY_DIR }}/{{ if eq .ISGROUP "true" }}group{{ else }}host{{ end }}_vars/{{ .OBJNAME }}'
    cmds:
      - cmd: 'echo "{{ .CONFIGFILE }} -> {{ .OUTPUT_DIR }}/99-config.secret.yml"'
        silent: true
      - mkdir -p "{{ .OUTPUT_DIR }}"
      - >
        op inject
        --in-file "{{ .CONFIGFILE }}"
        --out-file "{{ .OUTPUT_DIR }}/99-config.secret.yml"
        --force
      - sed -i '/^\s*#/d' "{{ .OUTPUT_DIR }}/99-config.secret.yml"
