---
all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
    internal_domain: internal.kreigan.com

proxmox_hosts:
  hosts:
    proxmox:
      ansible_host: proxmox.internal.kreigan.com
      proxmox_node_name: proxmox
  vars:
    service_type: proxmox

vms:
  hosts:
    storage:
      ansible_host: storage.internal.kreigan.com
      service_type: omv

containers:
  hosts:
    pihole:
      ansible_host: pihole.internal.kreigan.com
      service_type: pihole
      tls_cert_path: /etc/pihole/{{ internal_domain }}.pem

home:
  children:
    proxmox_hosts:
  hosts:
    storage:
    pihole:

webui:
  children:
    proxmox_hosts:
  hosts:
    storage:
    pihole:
