---

all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3

# ON PREM

onprem:
  hosts:
    proxmox01:
      ansible_host: "10.1.21.1"
    resolver01:
      ansible_host: "10.1.21.2"
    ns01:
      ansible_host: "10.1.21.3"
    pihole01:
      ansible_host: "10.1.21.5"
    gateway01:
      ansible_host: "10.1.21.10"
    docker01:
      ansible_host: "10.1.21.30"
  vars:
    cloud: false

proxmox_nodes:
  hosts:
    proxmox01:
      proxmox_node_name: proxmox

gateways:
  hosts:
    gateway01:

docker_nodes:
  hosts:
    docker01:

# CLOUD PROVIDERS

oracle:
  hosts:
  vars:
    cloud_provider: oracle

cloud:
  children:
    oracle:
  vars:
    cloud: true
