---

all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3

# ON PREM

onprem:
  hosts:
    proxmox01:
      ansible_host: &proxmox01 "10.1.21.1"
    resolver01:
      ansible_host: &resolver01 "10.1.21.2"
    pdnsdb01:
      ansible_host: &pdnsdb01 "10.1.21.6"
    ns01:
      ansible_host: &ns01 "10.1.21.3"
      pdnsdb_ip: *pdnsdb01
    ns02:
      ansible_host: &ns02 "10.1.21.4"
      pdnsdb_ip: *pdnsdb01
    pihole01:
      ansible_host: &pihole01 "10.1.21.5"
      pihole_webpassword: "op://homeops/pfr3zahxgtj6hmslbqa5lme5fq/password"
      pihole_dns_domain: "internal.kreigan.com"
      dns_pdns_ips:
        - *ns01
        - *ns02
      pihole_ftl_config:
        dns:
          upstreams:
            - *resolver01
          piholePTR: "HOSTNAME"
          queryLogging: false
          cache:
            size: 2000
          rateLimit:
            interval: 5
        dhcp:
          active: false
          start: "192.168.21.10"
          end: "192.168.21.99"
          router: "192.168.21.1"
          netmask: "255.255.255.0"
          leaseTime: "2d"
          rapidCommit: true
          multiDNS: true
        ntp:
          ipv4:
            active: false
          ipv6:
            active: false
          sync:
            interval: 0
        database:
          maxDBdays: 30
          network:
            expire: 30
        misc:
          dnsmasq_lines:
            - server=/kreigan.com/{{ dns_pdns_ips[0] }}
            - server=/kreigan.com/{{ dns_pdns_ips[1] }}
            - server=/internal.kreigan.com/{{ dns_pdns_ips[0] }}
            - server=/internal.kreigan.com/{{ dns_pdns_ips[1] }}
    gateway01:
      ansible_host: &gateway01 "10.1.21.20"
    docker01:
      ansible_host: &docker01 "10.1.21.30"
  vars:
    cloud: false

proxmox_nodes:
  hosts:
    proxmox01:
      proxmox_node_name: proxmox

dns:
  children:
    pihole:
      hosts:
        pihole01:
    powerdns:
      hosts:
        ns01:
        ns02:
    resolvers:
      hosts:
        resolver01:
  hosts:
    pdnsdb01:

gateways:
  hosts:
    gateway01:

docker_nodes:
  hosts:
    docker01:

# CLOUD PROVIDERS

oracle:
  hosts:
    ampere-vm:
      ansible_host: ampere-vm-cloud-services.kreigan.com
  vars:
    cloud_provider: oracle

cloud:
  children:
    oracle:
  vars:
    cloud: true
