---
all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
    internal_domain: internal.kreigan.com

# PROXMOX NODES

proxmox_nodes:
  hosts:
    prxvn01:
      ansible_host: proxmox.internal.kreigan.com
      proxmox_node_name: proxmox
  vars:
    service_type: proxmox

# CONTAINER HOSTS

containers:
  hosts:
    pihole:
      ansible_host: pihole.internal.kreigan.com
      service_type: pihole
      tls_cert_path: /etc/pihole/{{ internal_domain }}.pem
    proxy_internal:
      ansible_host: crnet01prx01.internal.kreigan.com
      ansible_user: root
      cloudflared: true

# CLOUD PROVIDER HOSTS

oracle:
  hosts:
    ampere_vm:
      ansible_host: ampere-vm-cloud-services.kreigan.com
      cloudflared: true
  vars:
    cloud_provider: oracle

cloud:
  children:
    oracle:
  vars:
    cloud: true

# DEVICES IN THE HOME NETWORK

home:
  children:
    proxmox_nodes:
  hosts:
    pihole:
    proxy_internal:
  vars:
    cloud: false

# SERVICES WITH WEB UI

webui:
  children:
    proxmox_nodes:
  hosts:
    pihole:

# PROXY SERVERS

proxies:
  hosts:
    proxy_internal:
    ampere_vm:
  vars:
    service_type: proxy
