caddy_routes_internal:

  # Proxmox WebUI
  - match:
      - host: ["pve.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: "home-proxmox01.int.kreigan.com:8006"
        transport:
          protocol: http
          tls:
            insecure_skip_verify: true
        headers:
          request:
            set:
              Host: ["home-proxmox01.int.kreigan.com"]
              Upgrade: ["{http.request.header.Upgrade}"]
              Connection: ["upgrade"]
          response:
            set:
              X-Frame-Options: ["SAMEORIGIN"]
        stream_timeout: "24h"

  # redirect Pi-hole WebUI to /admin
  - match:
      - host: ["adblock.int.kreigan.com"]
        path: ["/"]
    handle:
      - handler: static_response
        headers:
          Location: ["/admin{uri}"]
        status_code: 302

  # Pi-hole WebUI
  - match:
      - host: ["adblock.int.kreigan.com"]
    handle:
      - handler: encode
        encodings:
          gzip:
            level: 0
          zstd:
            level: fastest
      - handler: reverse_proxy
        upstreams:
          - dial: home-pihole.int.kreigan.com:80

  # NAS WebUI
  - match:
      - host: ["nas01ui.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: home-nas01.int.kreigan.com:8000

  # Sonarr
  - match:
      - host: ["sonarr.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: home-nas01.int.kreigan.com:18989

  # Radarr
  - match:
      - host: ["radarr.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: home-nas01.int.kreigan.com:17878

  # Prowlarr
  - match:
      - host: ["prowlarr.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: home-nas01.int.kreigan.com:29696

  # Bazarr
  - match:
      - host: ["bazarr.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: home-nas01.int.kreigan.com:16767
