caddy_routes_internal:

  # Proxmox WebUI
  - match:
      - host: ["pve.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: "home-proxmox01.int.kreigan.com:8006"
        transport:
          protocol: http
          tls:
            insecure_skip_verify: true
        headers:
          request:
            set:
              Host: ["home-proxmox01.int.kreigan.com"]
              Upgrade: ["{http.request.header.Upgrade}"]
              Connection: ["upgrade"]
          response:
            set:
              X-Frame-Options: ["SAMEORIGIN"]
        stream_timeout: "24h"

  # Portainer
  - match:
      - host: ["portainer.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: home-nas01.kreigan.com:19943
        transport:
          protocol: http
          tls:
            insecure_skip_verify: true

  # Internal qBittorrent
  - match:
      - host: ["qbt.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: home-nas01.kreigan.com:58080

  # PowerDNS webserver
  - match:
      - host: ["pdns-admin.int.kreigan.com"]
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: home-ns01.int.kreigan.com:8081

  # Cluster routes
  - match:
      - host:
          - "autobrr.int.kreigan.com"
          - "bazarr.int.kreigan.com"
          - "maintainerr.int.kreigan.com"
          - "prowlarr.int.kreigan.com"
          - "radarr.int.kreigan.com"
          - "recyclarr.int.kreigan.com"
          - "sonarr.int.kreigan.com"
          - "tautulli.int.kreigan.com"
    handle:
      - handler: reverse_proxy
        upstreams:
          - dial: homeks-gw01.int.kreigan.com:80
