postgresql_python_library: python3-psycopg2
postgresql_service_state: started
postgresql_service_enabled: true
postgresql_users:
  - name: &powerdns_user powerdns
    password: "{{ powerdns_db_password | mandatory }}"
    encrypted: true
postgresql_databases:
  - name: &powerdns_db powerdns
    owner: *powerdns_user
pdns_hba:
  type: host
  database: *powerdns_db
  user: *powerdns_user
  auth_method: md5
postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - "{{ pdns_hba | combine({'address': hostvars['ns01']['ansible_host'] + '/32'}) }}"
  - "{{ pdns_hba | combine({'address': hostvars['ns02']['ansible_host'] + '/32'}) }}"
