---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/refs/heads/main/src/ansiblelint/schemas/playbook.json
- name: Configure Pi-hole
  hosts: pihole
  roles:
    - pihole
  tags: pihole
