---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/refs/heads/main/src/ansiblelint/schemas/playbook.json
- name: Configure resolvers
  hosts: resolvers
  roles:
    - unbound
  tags: resolvers
