---
- name: Deploy proxy configuration
  block:
    - name: Deploy reverse proxy configurations
      ansible.builtin.template:
        src: proxy.conf.j2
        dest: "{{ nginx_config_dir }}/{{ item.name }}.conf"
        owner: "{{ nginx_proxy_service_user }}"
        group: "{{ nginx_proxy_service_user }}"
        mode: "0644"
        backup: true
      become: true
      register: nginx_proxy_conf_result
      notify: reload nginx

    - name: Validate deployed proxy configuration
      ansible.builtin.command: nginx -t
      become: true
      register: nginx_proxy_conf_validate
      changed_when: false
      failed_when: nginx_proxy_conf_validate.rc != 0

  rescue:
    - name: Rollback failed proxy configuration deployment
      ansible.builtin.copy:
        remote_src: true
        src: "{{ nginx_proxy_conf_result.backup_file }}"
        dest: "{{ nginx_config_dir }}/{{ item.name }}.conf"
        owner: "{{ nginx_proxy_service_user }}"
        group: "{{ nginx_proxy_service_user }}"
        mode: "0644"
      become: true
      notify: reload nginx

    - name: Move backup to temp location
      ansible.builtin.copy:
        remote_src: true
        src: "{{ nginx_proxy_conf_result.backup_file }}"
        dest: "/tmp/{{ nginx_proxy_conf_result.backup_file | basename }}"
        mode: "0644"
      become: true

    - name: Print error message for failed deployment
      ansible.builtin.debug:
        msg:
          - "Deployment of proxy configuration for {{ item.name }} failed and was rolled back."
          - "Please check the nginx configuration for errors."
          - "Backup file: {{ nginx_proxy_conf_result.backup_file }}"

  always:
    - name: Clean up backup file
      ansible.builtin.file:
        path: "{{ nginx_proxy_conf_result.backup_file }}"
        state: absent
      become: true
      when: nginx_proxy_conf_result.changed
