- name: Deploy TLS certificate
  vars:
    dest_dir: "{{ nginx_proxy_ssl_dest_dir }}/{{ cert.key }}"
  block:
    - name: Create certificate folder
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        owner: &nginx_user "{{ nginx_proxy_service_user }}"
        group: *nginx_user
        mode: "0750"

    - name: Deploy certificate files
      ansible.builtin.copy:
        src: "{{ cert_file }}"
        dest: "{{ dest_dir }}"
        owner: *nginx_user
        group: *nginx_user
        mode: "0644"
      loop: "{{ cert.value }}"
      loop_control:
        loop_var: cert_file
        label: "{{ cert_file }}"
      notify: reload nginx
